name: Update README

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  recent-activity:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: 'Checkout Repository'
        uses: actions/Checkout@v3
      - name: 'Update README.md'
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: '.github/recent-activity.config.yml'
  metrics:
    name: 'Update SVGs for Readme stats'
    runs-on: ubuntu-latest
    needs: recent-activity
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.user.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user
